#!/usr/bin/env bash
# Display "Best School" in stdout 10 times using while loop
# but for the 9th iteration, displays Best School and then Hi on a new line

index=0

while [ $index -lt 10 ]
do
    if [ $index -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    ((index++))
done