#!/usr/bin/env bash
# Displays "Best School" 10 times, "bad luck" at the 4th iteration,
# "good luck" at the 8th iteration

index=0

while [ $index -lt 10 ]
do
    if [ $index -eq 4 ];
    then 
        echo "bad luck"
    elif [ $index -eq 8 ];
    then
        echo "good luck"
    else
    echo "Best School"
    fi
    ((index++))
done
