#!/usr/bin/env bash
# Displays numbers from 1 - 20, displays 4 and then "bad luck from china"
# at the 4th iteration, displays 9 and then "bad luck from Japan" at the
# 9th iteration, displays 17 and then "bad luck from Italy" at the 17th
# iteration.

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((count++))
done