#!/usr/bin/env bash
# Displays hour from 0 - 12
# Displays minutes from 1 - 59

hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        ((minutes++))
    done
    ((hour++))
done